// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using RestaurantClient.Models;

namespace RestaurantClient.Models
{
    public static partial class SubscriptionCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Subscription> DeserializeJson(JToken inputObject)
        {
            IList<Subscription> deserializedObject = new List<Subscription>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Subscription subscription = new Subscription();
                subscription.DeserializeJson(iListValue);
                deserializedObject.Add(subscription);
            }
            return deserializedObject;
        }
    }
}
