// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace RestaurantClient.Models
{
    public partial class WaitTime
    {
        private int _groupNumber;
        
        /// <summary>
        /// Required.
        /// </summary>
        public int GroupNumber
        {
            get { return this._groupNumber; }
            set { this._groupNumber = value; }
        }
        
        private string _restaurantId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string RestaurantId
        {
            get { return this._restaurantId; }
            set { this._restaurantId = value; }
        }
        
        private int _wait;
        
        /// <summary>
        /// Required.
        /// </summary>
        public int Wait
        {
            get { return this._wait; }
            set { this._wait = value; }
        }
        
        private DateTimeOffset _waitDateTime;
        
        /// <summary>
        /// Required.
        /// </summary>
        public DateTimeOffset WaitDateTime
        {
            get { return this._waitDateTime; }
            set { this._waitDateTime = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the WaitTime class.
        /// </summary>
        public WaitTime()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the WaitTime class with required
        /// arguments.
        /// </summary>
        public WaitTime(int groupNumber, DateTimeOffset waitDateTime, int wait)
            : this()
        {
            this.GroupNumber = groupNumber;
            this.WaitDateTime = waitDateTime;
            this.Wait = wait;
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken groupNumberValue = inputObject["GroupNumber"];
                if (groupNumberValue != null && groupNumberValue.Type != JTokenType.Null)
                {
                    this.GroupNumber = ((int)groupNumberValue);
                }
                JToken restaurantIdValue = inputObject["RestaurantId"];
                if (restaurantIdValue != null && restaurantIdValue.Type != JTokenType.Null)
                {
                    this.RestaurantId = ((string)restaurantIdValue);
                }
                JToken waitValue = inputObject["Wait"];
                if (waitValue != null && waitValue.Type != JTokenType.Null)
                {
                    this.Wait = ((int)waitValue);
                }
                JToken waitDateTimeValue = inputObject["WaitDateTime"];
                if (waitDateTimeValue != null && waitDateTimeValue.Type != JTokenType.Null)
                {
                    this.WaitDateTime = ((DateTimeOffset)waitDateTimeValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type WaitTime
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            outputObject["GroupNumber"] = this.GroupNumber;
            if (this.RestaurantId != null)
            {
                outputObject["RestaurantId"] = this.RestaurantId;
            }
            outputObject["Wait"] = this.Wait;
            outputObject["WaitDateTime"] = this.WaitDateTime;
            return outputObject;
        }
    }
}
