// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using System.Net.Http;
using Microsoft.Rest;
using UserClient;

namespace UserClient
{
    public partial class RestaurantWaitTime : ServiceClient<RestaurantWaitTime>, IRestaurantWaitTime
    {
        private Uri _baseUri;
        
        /// <summary>
        /// The base URI of the service.
        /// </summary>
        public Uri BaseUri
        {
            get { return this._baseUri; }
            set { this._baseUri = value; }
        }
        
        private ServiceClientCredentials _credentials;
        
        /// <summary>
        /// Credentials for authenticating with the service.
        /// </summary>
        public ServiceClientCredentials Credentials
        {
            get { return this._credentials; }
            set { this._credentials = value; }
        }
        
        private IRestaurants _restaurants;
        
        public virtual IRestaurants Restaurants
        {
            get { return this._restaurants; }
        }
        
        private IRestaurantUsers _restaurantUsers;
        
        public virtual IRestaurantUsers RestaurantUsers
        {
            get { return this._restaurantUsers; }
        }
        
        private ISubscriptions _subscriptions;
        
        public virtual ISubscriptions Subscriptions
        {
            get { return this._subscriptions; }
        }
        
        private IUsers _users;
        
        public virtual IUsers Users
        {
            get { return this._users; }
        }
        
        private IWaitTimes _waitTimes;
        
        public virtual IWaitTimes WaitTimes
        {
            get { return this._waitTimes; }
        }
        
        /// <summary>
        /// Initializes a new instance of the RestaurantWaitTime class.
        /// </summary>
        public RestaurantWaitTime()
            : base()
        {
            this._restaurants = new Restaurants(this);
            this._restaurantUsers = new RestaurantUsers(this);
            this._subscriptions = new Subscriptions(this);
            this._users = new Users(this);
            this._waitTimes = new WaitTimes(this);
            this._baseUri = new Uri("https://restaurantwaittime.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the RestaurantWaitTime class.
        /// </summary>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public RestaurantWaitTime(params DelegatingHandler[] handlers)
            : base(handlers)
        {
            this._restaurants = new Restaurants(this);
            this._restaurantUsers = new RestaurantUsers(this);
            this._subscriptions = new Subscriptions(this);
            this._users = new Users(this);
            this._waitTimes = new WaitTimes(this);
            this._baseUri = new Uri("https://restaurantwaittime.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the RestaurantWaitTime class.
        /// </summary>
        /// <param name='rootHandler'>
        /// Optional. The http client handler used to handle http transport.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public RestaurantWaitTime(HttpClientHandler rootHandler, params DelegatingHandler[] handlers)
            : base(rootHandler, handlers)
        {
            this._restaurants = new Restaurants(this);
            this._restaurantUsers = new RestaurantUsers(this);
            this._subscriptions = new Subscriptions(this);
            this._users = new Users(this);
            this._waitTimes = new WaitTimes(this);
            this._baseUri = new Uri("https://restaurantwaittime.azurewebsites.net");
        }
        
        /// <summary>
        /// Initializes a new instance of the RestaurantWaitTime class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public RestaurantWaitTime(Uri baseUri, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            this._baseUri = baseUri;
        }
        
        /// <summary>
        /// Initializes a new instance of the RestaurantWaitTime class.
        /// </summary>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public RestaurantWaitTime(ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
        
        /// <summary>
        /// Initializes a new instance of the RestaurantWaitTime class.
        /// </summary>
        /// <param name='baseUri'>
        /// Optional. The base URI of the service.
        /// </param>
        /// <param name='credentials'>
        /// Required. Credentials for authenticating with the service.
        /// </param>
        /// <param name='handlers'>
        /// Optional. The set of delegating handlers to insert in the http
        /// client pipeline.
        /// </param>
        public RestaurantWaitTime(Uri baseUri, ServiceClientCredentials credentials, params DelegatingHandler[] handlers)
            : this(handlers)
        {
            if (baseUri == null)
            {
                throw new ArgumentNullException("baseUri");
            }
            if (credentials == null)
            {
                throw new ArgumentNullException("credentials");
            }
            this._baseUri = baseUri;
            this._credentials = credentials;
            
            if (this.Credentials != null)
            {
                this.Credentials.InitializeServiceClient(this);
            }
        }
    }
}
