// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace UserClient.Models
{
    public partial class Restaurant
    {
        private string _address;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Address
        {
            get { return this._address; }
            set { this._address = value; }
        }
        
        private string _capacity;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Capacity
        {
            get { return this._capacity; }
            set { this._capacity = value; }
        }
        
        private string _city;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string City
        {
            get { return this._city; }
            set { this._city = value; }
        }
        
        private string _cuisine;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Cuisine
        {
            get { return this._cuisine; }
            set { this._cuisine = value; }
        }
        
        private string _email;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Email
        {
            get { return this._email; }
            set { this._email = value; }
        }
        
        private string _hours;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Hours
        {
            get { return this._hours; }
            set { this._hours = value; }
        }
        
        private string _location;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Location
        {
            get { return this._location; }
            set { this._location = value; }
        }
        
        private string _name;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string Name
        {
            get { return this._name; }
            set { this._name = value; }
        }
        
        private string _phone;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Phone
        {
            get { return this._phone; }
            set { this._phone = value; }
        }
        
        private string _propertyID;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string PropertyID
        {
            get { return this._propertyID; }
            set { this._propertyID = value; }
        }
        
        private string _state;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string State
        {
            get { return this._state; }
            set { this._state = value; }
        }
        
        private string _webSite;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string WebSite
        {
            get { return this._webSite; }
            set { this._webSite = value; }
        }
        
        private string _zip;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string Zip
        {
            get { return this._zip; }
            set { this._zip = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Restaurant class.
        /// </summary>
        public Restaurant()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken addressValue = inputObject["Address"];
                if (addressValue != null && addressValue.Type != JTokenType.Null)
                {
                    this.Address = ((string)addressValue);
                }
                JToken capacityValue = inputObject["Capacity"];
                if (capacityValue != null && capacityValue.Type != JTokenType.Null)
                {
                    this.Capacity = ((string)capacityValue);
                }
                JToken cityValue = inputObject["City"];
                if (cityValue != null && cityValue.Type != JTokenType.Null)
                {
                    this.City = ((string)cityValue);
                }
                JToken cuisineValue = inputObject["Cuisine"];
                if (cuisineValue != null && cuisineValue.Type != JTokenType.Null)
                {
                    this.Cuisine = ((string)cuisineValue);
                }
                JToken emailValue = inputObject["Email"];
                if (emailValue != null && emailValue.Type != JTokenType.Null)
                {
                    this.Email = ((string)emailValue);
                }
                JToken hoursValue = inputObject["Hours"];
                if (hoursValue != null && hoursValue.Type != JTokenType.Null)
                {
                    this.Hours = ((string)hoursValue);
                }
                JToken locationValue = inputObject["Location"];
                if (locationValue != null && locationValue.Type != JTokenType.Null)
                {
                    this.Location = ((string)locationValue);
                }
                JToken nameValue = inputObject["Name"];
                if (nameValue != null && nameValue.Type != JTokenType.Null)
                {
                    this.Name = ((string)nameValue);
                }
                JToken phoneValue = inputObject["Phone"];
                if (phoneValue != null && phoneValue.Type != JTokenType.Null)
                {
                    this.Phone = ((string)phoneValue);
                }
                JToken propertyIDValue = inputObject["Property_ID"];
                if (propertyIDValue != null && propertyIDValue.Type != JTokenType.Null)
                {
                    this.PropertyID = ((string)propertyIDValue);
                }
                JToken stateValue = inputObject["State"];
                if (stateValue != null && stateValue.Type != JTokenType.Null)
                {
                    this.State = ((string)stateValue);
                }
                JToken webSiteValue = inputObject["WebSite"];
                if (webSiteValue != null && webSiteValue.Type != JTokenType.Null)
                {
                    this.WebSite = ((string)webSiteValue);
                }
                JToken zipValue = inputObject["Zip"];
                if (zipValue != null && zipValue.Type != JTokenType.Null)
                {
                    this.Zip = ((string)zipValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type Restaurant
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.City == null)
            {
                throw new ArgumentNullException("City");
            }
            if (this.Name == null)
            {
                throw new ArgumentNullException("Name");
            }
            if (this.State == null)
            {
                throw new ArgumentNullException("State");
            }
            if (this.Zip == null)
            {
                throw new ArgumentNullException("Zip");
            }
            if (this.Address != null)
            {
                outputObject["Address"] = this.Address;
            }
            if (this.Capacity != null)
            {
                outputObject["Capacity"] = this.Capacity;
            }
            if (this.City != null)
            {
                outputObject["City"] = this.City;
            }
            if (this.Cuisine != null)
            {
                outputObject["Cuisine"] = this.Cuisine;
            }
            if (this.Email != null)
            {
                outputObject["Email"] = this.Email;
            }
            if (this.Hours != null)
            {
                outputObject["Hours"] = this.Hours;
            }
            if (this.Location != null)
            {
                outputObject["Location"] = this.Location;
            }
            if (this.Name != null)
            {
                outputObject["Name"] = this.Name;
            }
            if (this.Phone != null)
            {
                outputObject["Phone"] = this.Phone;
            }
            if (this.PropertyID != null)
            {
                outputObject["Property_ID"] = this.PropertyID;
            }
            if (this.State != null)
            {
                outputObject["State"] = this.State;
            }
            if (this.WebSite != null)
            {
                outputObject["WebSite"] = this.WebSite;
            }
            if (this.Zip != null)
            {
                outputObject["Zip"] = this.Zip;
            }
            return outputObject;
        }
    }
}
